# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OfflineProtocolExample' do
  config = use_native_modules!

  # Manually add the local MeshSdk
  # Use frameworks for this pod to support custom module maps
  pod 'MeshSdk', :path => '../../../bindings/react-native/ios', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        other_cflags = build_config.build_settings['OTHER_CFLAGS'] || '$(inherited)'
        other_cxxflags = build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
        warning_flag = '-Wno-error=return-type'
        unless other_cflags.include?(warning_flag)
          build_config.build_settings['OTHER_CFLAGS'] = "#{other_cflags} #{warning_flag}"
        end
        unless other_cxxflags.include?(warning_flag)
          build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = "#{other_cxxflags} #{warning_flag}"
        end
        build_config.build_settings['SWIFT_STRICT_CONCURRENCY'] ||= 'minimal'
      end
      
      # Configure module map for MeshSdk pod
      if target.name == 'MeshSdk'
        target.build_configurations.each do |build_config|
          # Let CocoaPods generate its own module map
          build_config.build_settings['DEFINES_MODULE'] = 'YES'
          # Add path to the FFI module map so Swift can import offline_protocolFFI
          build_config.build_settings['SWIFT_INCLUDE_PATHS'] = '$(PODS_TARGET_SRCROOT)/Generated'
        end
      end
    end
  end
end
