"""The interface definition as data, generated. Do not edit.

Written by ``bindings/python/scripts/generate_local_api_table.py`` from
``crates/offline-protocol-uniffi/src/offline_protocol.udl``. A test
regenerates it in memory and fails when this file is stale, so every
change to the definition reaches the reference server as a diff here
and a classification in ``dispatch.py``.
"""

from __future__ import annotations

UDL_SHA256 = "d2b3a4e23be560b35388bfe45c5164ce4b7c002f5e11022700618c7e102823cb"

TABLE = {'callbacks': ('MlsStorageProvider',
               'ProtocolStateStorageProvider',
               'EventCallback',
               'BleTransportCallback',
               'WifiDirectTransportCallback',
               'ReticulumTransportCallback',
               'NostrTransportCallback'),
 'enums': {'AppState': ('Active', 'Background', 'Inactive'),
           'ContentType': ('Text',
                           'Image',
                           'Video',
                           'Audio',
                           'VoiceNote',
                           'VideoNote',
                           'File',
                           'FileChunk',
                           'Poll'),
           'EstablishmentState': ('NoKeyPackage',
                                  'HaveKeyPackage',
                                  'SessionPending',
                                  'SessionConfirmed'),
           'MessagePriority': ('Low', 'Medium', 'High', 'Critical'),
           'MlsVerbosity': ('Off', 'Lifecycle', 'Diagnostic'),
           'OverflowPolicy': ('DropOldest', 'DropNewest'),
           'PresenceStatus': ('Online', 'Away', 'Offline'),
           'ProtocolState': ('Stopped', 'Running', 'Paused'),
           'RelayPriority': ('Never', 'Auto', 'Always'),
           'RelaySyncState': ('Synced', 'Pending', 'Unsynced'),
           'TelemetryOs': ('Ios', 'Android', 'Linux', 'Macos', 'Windows', 'Other'),
           'TransportType': ('Internet', 'Ble', 'WiFiDirect', 'Reticulum', 'Nostr')},
 'errors': {'MlsStorageError': ('StoreFailed',
                                'LoadFailed',
                                'DeleteFailed',
                                'KeyNotFound',
                                'CorruptedData'),
            'ProtocolError': ('NotStarted',
                              'AlreadyStarted',
                              'InvalidConfiguration',
                              'SendFailed',
                              'NoKeyPackage',
                              'SessionNotReady',
                              'EncryptFailed',
                              'InvalidState',
                              'MlsNotInitialized',
                              'MlsError',
                              'UserBlocked',
                              'MediaTransferLimit',
                              'LockPoisoned',
                              'Other',
                              'TransportError',
                              'SerializationError',
                              'ServiceError',
                              'GroupNotFound',
                              'PermissionDenied',
                              'InvalidArgument',
                              'DataDisabled',
                              'DataStorageUnavailable',
                              'DocTooLarge',
                              'DataCorrupted',
                              'TelemetryConfigInvalid')},
 'methods': {'DataStore': {'attachment_hash': ((('data', 'bytes'),), 'string'),
                           'constructor': ((('protocol', 'OfflineProtocol'),), 'object'),
                           'counter_increment': ((('space_id', 'string'),
                                                  ('doc_id', 'string'),
                                                  ('collection', 'string'),
                                                  ('amount', 'double')),
                                                 'void'),
                           'counter_value': ((('space_id', 'string'),
                                              ('doc_id', 'string'),
                                              ('collection', 'string')),
                                             'double'),
                           'create_doc': ((('space_id', 'string'), ('doc_id', 'string')), 'void'),
                           'decline_attachment': ((('space_id', 'string'),
                                                   ('peer_id', 'string'),
                                                   ('hash', 'string')),
                                                  'void'),
                           'delete_doc': ((('space_id', 'string'), ('doc_id', 'string')), 'void'),
                           'doc_json': ((('space_id', 'string'), ('doc_id', 'string')), 'string'),
                           'doc_size': ((('space_id', 'string'), ('doc_id', 'string')), 'u64'),
                           'export_raw': ((('space_id', 'string'), ('doc_id', 'string')), 'bytes'),
                           'fetch_attachment': ((('space_id', 'string'), ('hash', 'string')),
                                                'void'),
                           'fetch_attachment_from': ((('space_id', 'string'),
                                                      ('peer_id', 'string'),
                                                      ('hash', 'string')),
                                                     'void'),
                           'flush': ((('space_id', 'string'), ('doc_id', 'string')), 'void'),
                           'flush_all': ((), 'void'),
                           'list_delete': ((('space_id', 'string'),
                                            ('doc_id', 'string'),
                                            ('collection', 'string'),
                                            ('index', 'u32'),
                                            ('count', 'u32')),
                                           'void'),
                           'list_docs': ((('space_id', 'string'),), 'sequence<string>'),
                           'list_len': ((('space_id', 'string'),
                                         ('doc_id', 'string'),
                                         ('collection', 'string')),
                                        'u32'),
                           'list_push': ((('space_id', 'string'),
                                          ('doc_id', 'string'),
                                          ('collection', 'string'),
                                          ('value_json', 'string')),
                                         'void'),
                           'list_spaces': ((), 'sequence<string>'),
                           'map_delete': ((('space_id', 'string'),
                                           ('doc_id', 'string'),
                                           ('collection', 'string'),
                                           ('key', 'string')),
                                          'void'),
                           'map_get_json': ((('space_id', 'string'),
                                             ('doc_id', 'string'),
                                             ('collection', 'string'),
                                             ('key', 'string')),
                                            'string?'),
                           'map_set': ((('space_id', 'string'),
                                        ('doc_id', 'string'),
                                        ('collection', 'string'),
                                        ('key', 'string'),
                                        ('value_json', 'string')),
                                       'void'),
                           'provide_attachment': ((('space_id', 'string'),
                                                   ('peer_id', 'string'),
                                                   ('hash', 'string'),
                                                   ('data', 'bytes')),
                                                  'void'),
                           'remove_doc': ((('space_id', 'string'), ('doc_id', 'string')), 'void'),
                           'remove_space': ((('space_id', 'string'),), 'void'),
                           'set_interest': ((('space_id', 'string'),
                                             ('patterns', 'sequence<string>')),
                                            'void'),
                           'text_delete': ((('space_id', 'string'),
                                            ('doc_id', 'string'),
                                            ('collection', 'string'),
                                            ('position', 'u32'),
                                            ('count', 'u32')),
                                           'void'),
                           'text_insert': ((('space_id', 'string'),
                                            ('doc_id', 'string'),
                                            ('collection', 'string'),
                                            ('position', 'u32'),
                                            ('text', 'string')),
                                           'void'),
                           'text_value': ((('space_id', 'string'),
                                           ('doc_id', 'string'),
                                           ('collection', 'string')),
                                          'string'),
                           'wipe_all': ((), 'void'),
                           'with_storage': ((('protocol', 'OfflineProtocol'),
                                             ('storage', 'ProtocolStateStorageProvider')),
                                            'object')},
             'MeshServices': {'constructor': ((('protocol', 'OfflineProtocol'),), 'object'),
                              'discover_services': ((('service_id', 'string?'),), 'string'),
                              'register_service': ((('service_id', 'string'),
                                                    ('version', 'string'),
                                                    ('capabilities', 'record<DOMString,string>')),
                                                   'void'),
                              'respond_to_service_request': ((('request_id', 'string'),
                                                              ('requester', 'string'),
                                                              ('service_id', 'string'),
                                                              ('status', 'string'),
                                                              ('body', 'string')),
                                                             'string'),
                              'send_service_request': ((('provider', 'string'),
                                                        ('service_id', 'string'),
                                                        ('method', 'string'),
                                                        ('body', 'string')),
                                                       'string'),
                              'unregister_service': ((('service_id', 'string'),), 'boolean')},
             'OfflineProtocol': {'accept_connection_request': ((('recipient', 'string'),
                                                                ('accepter_name', 'string'),
                                                                ('key_package', 'sequence<u8>?')),
                                                               'string'),
                                 'ble_clear_peer_mtu': ((('peer_id', 'string'),), 'void'),
                                 'ble_fragment_fallback_count': ((), 'u64'),
                                 'ble_fragment_received': ((('sender_id', 'string'),
                                                            ('fragment', 'sequence<u8>')),
                                                           'void'),
                                 'ble_get_next_fragment': ((), 'BleFragment?'),
                                 'ble_get_peer_count': ((), 'u32'),
                                 'ble_peer_discovered': ((('peer_id', 'string'), ('rssi', 'i16')),
                                                         'void'),
                                 'ble_peer_lost': ((('peer_id', 'string'),), 'void'),
                                 'ble_recipient_not_among_peers_count': ((), 'u64'),
                                 'ble_return_fragment': ((), 'void'),
                                 'ble_set_peer_mtu': ((('peer_id', 'string'),
                                                       ('max_payload', 'u32')),
                                                      'void'),
                                 'ble_status_changed': ((('is_available', 'boolean'),), 'void'),
                                 'ble_undersized_mtu_reports': ((), 'u64'),
                                 'block_user': ((('user_id', 'string'),), 'void'),
                                 'cancel_connection_request': ((('recipient', 'string'),),
                                                               'string'),
                                 'cancel_file_transfer': ((('file_id', 'string'),), 'void'),
                                 'close_file_stores': ((), 'void'),
                                 'constructor': ((('config', 'ProtocolConfig'),), 'object'),
                                 'create_group': ((('group_name', 'string'),), 'MlsGroupInfo'),
                                 'create_invite': ((('petname', 'string?'), ('sign', 'boolean')),
                                                   'string'),
                                 'derive_user_id_from_public_key': ((('public_key',
                                                                      'sequence<u8>'),),
                                                                    'string'),
                                 'disable_telemetry': ((), 'void'),
                                 'emit_test_event': ((), 'void'),
                                 'enable_telemetry': ((('config', 'TelemetryConfig'),
                                                       ('app_state', 'AppState')),
                                                      'void'),
                                 'end_telemetry_session': ((), 'void'),
                                 'erase_custody': ((), 'void'),
                                 'establish_secure_session': ((('peer_id', 'string'),),
                                                              'MlsWelcomeMessage?'),
                                 'finalize_file': ((('file_id', 'string'),), 'void'),
                                 'flush_telemetry': ((), 'void'),
                                 'flush_telemetry_blocking': ((('deadline_ms', 'u64'),), 'boolean'),
                                 'force_transport': ((('transport_type', 'TransportType'),),
                                                     'void'),
                                 'forward_message': ((('original_message_json', 'string'),
                                                      ('new_recipient', 'string'),
                                                      ('priority', 'MessagePriority?')),
                                                     'string'),
                                 'forward_message_to_group': ((('original_message_json', 'string'),
                                                               ('group_id', 'string'),
                                                               ('priority', 'MessagePriority?')),
                                                              'sequence<string>'),
                                 'gateway_address_declaration': ((('challenge', 'sequence<u8>'),),
                                                                 'GatewayAddressDeclaration'),
                                 'get_active_transports': ((), 'sequence<string>'),
                                 'get_battery_level': ((), 'u8?'),
                                 'get_blocked_users': ((), 'sequence<string>'),
                                 'get_custody_stats': ((), 'CustodyStats'),
                                 'get_dedup_stats': ((), 'DedupStats'),
                                 'get_delivery_success_rate': ((), 'f32'),
                                 'get_dors_config': ((), 'DorsConfig'),
                                 'get_establishment_state': ((('peer_id', 'string'),),
                                                             'EstablishmentState'),
                                 'get_file_progress': ((('file_id', 'string'),), 'FileProgress?'),
                                 'get_group_info': ((('group_id', 'string'),), 'MlsGroupInfo?'),
                                 'get_group_roles': ((('group_id', 'string'),),
                                                     'record<DOMString,string>'),
                                 'get_identity_public_key': ((), 'sequence<u8>'),
                                 'get_is_charging': ((), 'boolean'),
                                 'get_median_hops': ((), 'u8'),
                                 'get_median_latency': ((), 'u64'),
                                 'get_member_role': ((('group_id', 'string'),
                                                      ('user_id', 'string')),
                                                     'string'),
                                 'get_mesh_relay_stats': ((), 'MeshRelayStats'),
                                 'get_mesh_relay_tunables': ((), 'MeshRelayTunables'),
                                 'get_message_stats': ((), 'sequence<MessageStats>'),
                                 'get_pending_ack_count': ((), 'u64'),
                                 'get_relay_config': ((), 'RelayConfig'),
                                 'get_relay_priority': ((), 'RelayPriority'),
                                 'get_retry_queue_size': ((), 'u64'),
                                 'get_state': ((), 'ProtocolState'),
                                 'get_topology': ((), 'NetworkTopology'),
                                 'get_transport_metrics': ((('transport_type', 'TransportType'),),
                                                           'TransportMetrics?'),
                                 'group_relay_sync_state': ((('group_id', 'string'),),
                                                            'RelaySyncState'),
                                 'group_rich_readiness': ((('group_id', 'string'),),
                                                          'GroupRichReadiness'),
                                 'has_pending_key_package': ((('peer_id', 'string'),), 'boolean'),
                                 'identity_assertion': ((('signed_data', 'sequence<u8>'),),
                                                        'sequence<u8>'),
                                 'initialize_mls': ((('secure_storage', 'MlsStorageProvider'),
                                                     ('protocol_state_storage',
                                                      'ProtocolStateStorageProvider')),
                                                    'void'),
                                 'initialize_mls_with_file_stores': ((('mls_root', 'string'),
                                                                      ('state_root', 'string'),
                                                                      ('store_key', 'bytes')),
                                                                     'void'),
                                 'internet_address_declaration_refused': ((('reason', 'string'),),
                                                                          'void'),
                                 'internet_address_declared': ((('address', 'string'),), 'void'),
                                 'internet_confirm_sent': ((('message_id', 'string'),), 'void'),
                                 'internet_get_next_message': ((), 'InternetMessage?'),
                                 'internet_group_report_received': ((('report_json', 'string'),),
                                                                    'void'),
                                 'internet_message_received': ((('sender_id', 'string'),
                                                                ('data', 'sequence<u8>')),
                                                               'void'),
                                 'internet_peer_presence': ((('peer_id', 'string'),
                                                             ('online', 'boolean'),
                                                             ('last_seen_ms', 'i64?')),
                                                            'void'),
                                 'internet_presence_watchlist': ((), 'sequence<string>'),
                                 'internet_relay_capabilities': ((('capabilities',
                                                                   'sequence<string>'),),
                                                                 'void'),
                                 'internet_send_failed': ((('message_id', 'string'),), 'void'),
                                 'internet_send_failed_with_reason': ((('message_id', 'string'),
                                                                       ('reason', 'string?')),
                                                                      'void'),
                                 'internet_status_changed': ((('is_connected', 'boolean'),),
                                                             'void'),
                                 'invite_to_group': ((('group_id', 'string'),
                                                      ('invitee_user_id', 'string')),
                                                     'void'),
                                 'is_mls_initialized': ((), 'boolean'),
                                 'is_relay': ((), 'boolean'),
                                 'is_user_blocked': ((('user_id', 'string'),), 'boolean'),
                                 'leave_group': ((('group_id', 'string'),), 'void'),
                                 'list_groups': ((), 'sequence<string>'),
                                 'local_address': ((), 'string?'),
                                 'mls_clear_pending_welcome': ((('other_user_id', 'string'),),
                                                               'void'),
                                 'mls_create_session': ((('other_user_id', 'string'),),
                                                        'MlsWelcomeMessage'),
                                 'mls_decrypt': ((('encrypted', 'MlsEncryptedMessage'),),
                                                 'sequence<u8>?'),
                                 'mls_decrypt_from_user': ((('encrypted', 'MlsEncryptedMessage'),),
                                                           'sequence<u8>?'),
                                 'mls_delete_session': ((('other_user_id', 'string'),), 'void'),
                                 'mls_encrypt_for_user': ((('other_user_id', 'string'),
                                                           ('plaintext', 'sequence<u8>')),
                                                          'MlsEncryptedMessage'),
                                 'mls_generate_key_package': ((), 'MlsKeyPackageBundle'),
                                 'mls_get_or_create_key_package': ((), 'MlsKeyPackageBundle'),
                                 'mls_get_pending_key_packages': ((),
                                                                  'sequence<MlsKeyPackageBundle>'),
                                 'mls_get_pending_welcome': ((('other_user_id', 'string'),),
                                                             'MlsWelcomeMessage?'),
                                 'mls_has_session': ((('other_user_id', 'string'),), 'boolean'),
                                 'mls_import_key_package': ((('user_id', 'string'),
                                                             ('key_package_data', 'sequence<u8>')),
                                                            'void'),
                                 'mls_join_session': ((('welcome', 'MlsWelcomeMessage'),),
                                                      'MlsGroupInfo'),
                                 'mls_list_sessions': ((), 'sequence<string>'),
                                 'mls_mark_key_package_synced': ((('package_id', 'string'),),
                                                                 'void'),
                                 'mls_process_welcome': ((('welcome', 'MlsWelcomeMessage'),),
                                                         'MlsGroupInfo'),
                                 'nostr_confirm_sent': ((('message_id', 'string'),), 'void'),
                                 'nostr_get_next_message': ((), 'NostrMessage?'),
                                 'nostr_get_next_query': ((), 'NostrQuery?'),
                                 'nostr_get_public_key': ((), 'string?'),
                                 'nostr_get_subscription_filter': ((('subscription_id', 'string'),),
                                                                   'string?'),
                                 'nostr_message_received': ((('sender_id', 'string'),
                                                             ('data', 'sequence<u8>')),
                                                            'void'),
                                 'nostr_message_received_at': ((('sender_id', 'string'),
                                                                ('data', 'sequence<u8>'),
                                                                ('created_at', 'i64')),
                                                               'void'),
                                 'nostr_query_completed': ((('query_id', 'string'),), 'void'),
                                 'nostr_query_event_received': ((('query_id', 'string'),
                                                                 ('event_json', 'string')),
                                                                'void'),
                                 'nostr_send_failed': ((('message_id', 'string'),), 'void'),
                                 'nostr_send_failed_with_reason': ((('message_id', 'string'),
                                                                    ('reason', 'string?')),
                                                                   'void'),
                                 'nostr_status_changed': ((('is_connected', 'boolean'),), 'void'),
                                 'notify_app_state': ((('state', 'AppState'),), 'void'),
                                 'pause': ((), 'void'),
                                 'poll_event': ((), 'string?'),
                                 'process': ((), 'void'),
                                 'process_file_chunk': ((('file_id', 'string'),
                                                         ('chunk_index', 'u32'),
                                                         ('total_chunks', 'u32'),
                                                         ('file_size', 'u64'),
                                                         ('file_name', 'string'),
                                                         ('file_checksum', 'string'),
                                                         ('data', 'sequence<u8>')),
                                                        'void'),
                                 'protocol_lock_diagnostics': ((), 'ProtocolLockDiagnostics'),
                                 'receive_message': ((), 'string?'),
                                 'reject_connection_request': ((('recipient', 'string'),),
                                                               'string'),
                                 'rekey_session': ((('peer_id', 'string'),), 'boolean'),
                                 'release_transport_lock': ((), 'void'),
                                 'remove_from_group': ((('group_id', 'string'),
                                                        ('member_id', 'string')),
                                                       'void'),
                                 'remove_transport': ((('transport_type', 'TransportType'),),
                                                      'void'),
                                 'rename_group': ((('group_id', 'string'), ('new_name', 'string')),
                                                  'void'),
                                 'request_group_relay_registration': ((('group_id', 'string'),),
                                                                      'boolean'),
                                 'resolve_username': ((('username', 'string'),), 'boolean'),
                                 'resume': ((), 'void'),
                                 'reticulum_address_declaration_refused': ((('reason', 'string'),),
                                                                           'void'),
                                 'reticulum_address_declared': ((('address', 'string'),), 'void'),
                                 'reticulum_confirm_sent': ((('message_id', 'string'),), 'void'),
                                 'reticulum_gateway_capabilities': ((('capabilities',
                                                                      'sequence<string>'),),
                                                                    'void'),
                                 'reticulum_get_next_message': ((), 'ReticulumMessage?'),
                                 'reticulum_message_received': ((('sender_id', 'string'),
                                                                 ('data', 'sequence<u8>')),
                                                                'void'),
                                 'reticulum_peer_presence': ((('peer_id', 'string'),
                                                              ('online', 'boolean'),
                                                              ('last_seen_ms', 'i64?')),
                                                             'void'),
                                 'reticulum_presence_watchlist': ((), 'sequence<string>'),
                                 'reticulum_send_failed': ((('message_id', 'string'),), 'void'),
                                 'reticulum_send_failed_with_reason': ((('message_id', 'string'),
                                                                        ('reason', 'string?')),
                                                                       'void'),
                                 'reticulum_status_changed': ((('is_connected', 'boolean'),),
                                                              'void'),
                                 'send_connection_request': ((('recipient', 'string'),
                                                              ('sender_name', 'string'),
                                                              ('key_package', 'sequence<u8>?'),
                                                              ('initial_message', 'string?')),
                                                             'string'),
                                 'send_file': ((('recipient', 'string'),
                                                ('file_data', 'sequence<u8>'),
                                                ('file_name', 'string')),
                                               'string'),
                                 'send_group_message': ((('group_id', 'string'),
                                                         ('content', 'string'),
                                                         ('priority', 'MessagePriority?'),
                                                         ('reply_to_msg', 'string?')),
                                                        'sequence<string>'),
                                 'send_media': ((('recipient', 'string'),
                                                 ('file_data', 'sequence<u8>'),
                                                 ('file_name', 'string'),
                                                 ('content_type', 'ContentType'),
                                                 ('media_metadata', 'MediaMetadata?')),
                                                'string'),
                                 'send_media_rich': ((('recipient', 'string'),
                                                      ('file_data', 'sequence<u8>'),
                                                      ('file_name', 'string'),
                                                      ('content_type', 'ContentType'),
                                                      ('options', 'MediaSendOptions')),
                                                     'string'),
                                 'send_message': ((('recipient', 'string'),
                                                   ('content', 'string'),
                                                   ('priority', 'MessagePriority'),
                                                   ('reply_to_msg', 'string?')),
                                                  'string'),
                                 'send_message_rich': ((('recipient', 'string'),
                                                        ('content', 'string'),
                                                        ('options', 'SendMessageOptions')),
                                                       'string'),
                                 'send_presence_update': ((('recipient', 'string'),
                                                           ('status', 'PresenceStatus')),
                                                          'string'),
                                 'send_read_receipt': ((('recipient', 'string'),
                                                        ('message_ids', 'sequence<string>')),
                                                       'string'),
                                 'send_typing_indicator': ((('recipient', 'string'),
                                                            ('conversation_id', 'string'),
                                                            ('is_typing', 'boolean')),
                                                           'string'),
                                 'set_battery_level': ((('level', 'u8'),), 'void'),
                                 'set_battery_state': ((('level', 'u8'),
                                                        ('is_charging', 'boolean')),
                                                       'void'),
                                 'set_ble_transport_callback': ((('callback',
                                                                  'BleTransportCallback'),),
                                                                'void'),
                                 'set_event_callback': ((('callback', 'EventCallback'),), 'void'),
                                 'set_member_role': ((('group_id', 'string'),
                                                      ('user_id', 'string'),
                                                      ('role', 'string')),
                                                     'void'),
                                 'set_nostr_transport_callback': ((('callback',
                                                                    'NostrTransportCallback'),),
                                                                  'void'),
                                 'set_relay_priority': ((('priority', 'RelayPriority'),), 'void'),
                                 'set_reticulum_transport_callback': ((('callback',
                                                                        'ReticulumTransportCallback'),),
                                                                      'void'),
                                 'set_telemetry_enabled': ((('enabled', 'boolean'),), 'void'),
                                 'set_wifi_direct_transport_callback': ((('callback',
                                                                          'WifiDirectTransportCallback'),),
                                                                        'void'),
                                 'should_escalate_to_wifi': ((), 'boolean'),
                                 'sign_data': ((('data', 'sequence<u8>'),), 'sequence<u8>'),
                                 'start': ((), 'void'),
                                 'stop': ((), 'void'),
                                 'telemetry_install_id': ((), 'string?'),
                                 'telemetry_stats': ((), 'TelemetryStats?'),
                                 'unblock_user': ((('user_id', 'string'),), 'void'),
                                 'update_ack_config': ((('config', 'AckConfig'),), 'void'),
                                 'update_dedup_config': ((('config', 'DedupConfig'),), 'void'),
                                 'update_dors_config': ((('config', 'DorsConfig'),), 'void'),
                                 'update_relay_config': ((('config', 'RelayConfig'),), 'void'),
                                 'update_retry_config': ((('config', 'RetryConfig'),), 'void'),
                                 'update_transport_metrics': ((('transport_type', 'TransportType'),
                                                               ('metrics', 'TransportMetrics')),
                                                              'void'),
                                 'verify_signature': ((('public_key', 'sequence<u8>'),
                                                       ('data', 'sequence<u8>'),
                                                       ('signature', 'sequence<u8>')),
                                                      'boolean'),
                                 'wifi_direct_get_next_message': ((), 'WifiDirectMessage?'),
                                 'wifi_direct_message_received': ((('sender_id', 'string'),
                                                                   ('data', 'sequence<u8>')),
                                                                  'void'),
                                 'wifi_direct_peer_connected': ((('peer_id', 'string'),), 'void'),
                                 'wifi_direct_peer_disconnected': ((('peer_id', 'string'),),
                                                                   'void'),
                                 'wifi_direct_status_changed': ((('is_connected', 'boolean'),),
                                                                'void')},
             'namespace': {'derive_address': ((('public_key', 'sequence<u8>'),), 'string'),
                           'parse_invite': ((('blob', 'string'),), 'InviteInfo'),
                           'run_storage_conformance': ((('storage',
                                                         'ProtocolStateStorageProvider'),),
                                                       'string'),
                           'verify_identity_assertion': ((('assertion', 'sequence<u8>'),),
                                                         'string')}},
 'records': {'AckConfig': (('default_timeout_ms', 'u64', False),
                           ('max_pending_acks', 'u64', False)),
             'BleFragment': (('recipient_id', 'string', False), ('data', 'sequence<u8>', False)),
             'CustodyConfig': (('enabled', 'boolean?', True),
                               ('hold_ms', 'u64?', True),
                               ('max_entries_per_depositor', 'u64?', True),
                               ('max_bytes_per_depositor', 'u64?', True),
                               ('max_entries', 'u64?', True),
                               ('max_bytes', 'u64?', True),
                               ('stranger_max_entries', 'u64?', True),
                               ('stranger_max_bytes', 'u64?', True),
                               ('overflow_policy', 'OverflowPolicy?', True)),
             'CustodyStats': (('held', 'u64', False),
                              ('held_bytes', 'u64', False),
                              ('accepted', 'u64', False),
                              ('delivered', 'u64', False),
                              ('re_originated', 'u64', False),
                              ('expired', 'u64', False),
                              ('duplicates', 'u64', False),
                              ('evicted', 'u64', False),
                              ('receipts_sent', 'u64', False),
                              ('receipts_dropped', 'u64', False),
                              ('receipts_received', 'u64', False),
                              ('receipts_ignored', 'u64', False),
                              ('refused_disabled', 'u64', False),
                              ('refused_no_request', 'u64', False),
                              ('refused_unknown_class', 'u64', False),
                              ('refused_not_sealed', 'u64', False),
                              ('refused_unproven_peer', 'u64', False),
                              ('refused_not_depositor', 'u64', False),
                              ('refused_stranger', 'u64', False),
                              ('refused_depositor_full', 'u64', False),
                              ('refused_store_full', 'u64', False),
                              ('refused_battery', 'u64', False)),
             'DedupConfig': (('max_tracked_messages', 'u64', False),
                             ('retention_time_secs', 'u64', False)),
             'DedupStats': (('total_tracked', 'u64', False),
                            ('recent_tracked', 'u64', False),
                            ('capacity_used_percent', 'u8', False),
                            ('mode', 'string', False)),
             'DorsConfig': (('prefer_online', 'boolean', False),
                            ('switch_hysteresis', 'f32', False),
                            ('switch_cooldown_secs', 'u64', False),
                            ('ble_to_wifi_retry_threshold', 'u32', False),
                            ('min_success_rate_before_escalation', 'f32', False),
                            ('min_ble_samples_before_success_rate_escalation', 'u64', False),
                            ('rssi_switch_threshold', 'i16', False),
                            ('congestion_queue_threshold', 'u64', False),
                            ('stability_window_secs', 'u64', False),
                            ('poor_signal_duration_secs', 'u64', False),
                            ('ttl_escalation_threshold', 'u8', False),
                            ('congestion_duration_secs', 'u64', False),
                            ('ttl_escalation_hold_secs', 'u64', False),
                            ('history_window_size', 'u64', False),
                            ('queue_recovery_ratio', 'f32', False),
                            ('low_battery_threshold', 'u8', False),
                            ('relay_min_battery_level', 'u8', False),
                            ('relay_optimal_connection_count', 'u8', False)),
             'EncryptionConfig': (('enabled', 'boolean', False),
                                  ('auto_key_exchange', 'boolean', False),
                                  ('store_pending', 'boolean', False),
                                  ('require_encryption', 'boolean', True),
                                  ('pending_queue', 'PendingQueueConfig', False)),
             'FileProgress': (('file_id', 'string', False),
                              ('chunks_sent', 'u32', False),
                              ('total_chunks', 'u32', False),
                              ('percentage', 'u8', False)),
             'ForwardInfo': (('original_sender', 'string', False),
                             ('original_message_id', 'string', False),
                             ('original_timestamp', 'i64', False),
                             ('forward_count', 'u32', False)),
             'GatewayAddressDeclaration': (('address', 'string', False),
                                           ('public_key', 'sequence<u8>', False),
                                           ('signature', 'sequence<u8>', False)),
             'GroupRichReadiness': (('ready', 'boolean', False),
                                    ('unknown_members', 'sequence<string>', False)),
             'InternetMessage': (('message_id', 'string', False),
                                 ('recipient_id', 'string', False),
                                 ('data', 'sequence<u8>', False),
                                 ('reply_to_msg', 'string?', False),
                                 ('control_op', 'string?', False),
                                 ('control_payload', 'string?', False)),
             'InviteInfo': (('address', 'string', False),
                            ('public_key', 'sequence<u8>', False),
                            ('petname', 'string?', False),
                            ('signed', 'boolean', False)),
             'MediaMetadata': (('mime_type', 'string', False),
                               ('file_name', 'string', False),
                               ('file_size', 'u64', False),
                               ('duration_ms', 'u64?', False),
                               ('width', 'u32?', False),
                               ('height', 'u32?', False),
                               ('thumbnail_base64', 'string?', False),
                               ('media_id', 'string?', True),
                               ('download_url', 'string?', True),
                               ('thumbnail_url', 'string?', True),
                               ('encryption_key', 'string?', True),
                               ('iv', 'string?', True),
                               ('ciphertext_hash', 'string?', True),
                               ('sticker_provider', 'string?', True),
                               ('sticker_remote_id', 'string?', True),
                               ('sticker_kind', 'string?', True)),
             'MediaSendOptions': (('media_metadata', 'MediaMetadata?', True),
                                  ('caption', 'string?', True),
                                  ('reply_to_msg', 'string?', True),
                                  ('reply_context', 'ReplyContext?', True),
                                  ('forward_info', 'ForwardInfo?', True),
                                  ('file_id', 'string?', True),
                                  ('app_id', 'string?', True)),
             'MeshRelayConfig': (('max_ttl', 'u8?', True),
                                 ('dense_max_ttl', 'u8?', True),
                                 ('dense_degree', 'u64?', True),
                                 ('fanout', 'u64?', True),
                                 ('jitter_min_ms', 'u64?', True),
                                 ('jitter_max_ms', 'u64?', True),
                                 ('rate_per_sec', 'f32?', True),
                                 ('burst', 'f32?', True),
                                 ('peer_rate_per_sec', 'f32?', True),
                                 ('peer_burst', 'f32?', True),
                                 ('queue_capacity', 'u64?', True),
                                 ('bias_min_scale', 'f32?', True),
                                 ('bias_max_handicap_ms', 'u64?', True),
                                 ('activity_window_ms', 'u64?', True),
                                 ('activity_min_forwards', 'u64?', True),
                                 ('activity_idle_windows', 'u32?', True)),
             'MeshRelayStats': (('forwarded', 'u64', False),
                                ('transmissions', 'u64', False),
                                ('queued', 'u64', False),
                                ('awaiting_transmission', 'u64', False),
                                ('duplicates_suppressed', 'u64', False),
                                ('covered_by_a_neighbor', 'u64', False),
                                ('peer_rate_limited', 'u64', False),
                                ('refused_queue_full', 'u64', False),
                                ('rate_deferred', 'u64', False),
                                ('abandoned_overdue', 'u64', False),
                                ('hop_limit_reached', 'u64', False),
                                ('reach_clamped', 'u64', False),
                                ('dropped_for_capacity', 'u64', False)),
             'MeshRelayTunables': (('max_ttl', 'u8', False),
                                   ('dense_max_ttl', 'u8', False),
                                   ('dense_degree', 'u64', False),
                                   ('fanout', 'u64', False),
                                   ('jitter_min_ms', 'u64', False),
                                   ('jitter_max_ms', 'u64', False),
                                   ('rate_per_sec', 'f32', False),
                                   ('burst', 'f32', False),
                                   ('peer_rate_per_sec', 'f32', False),
                                   ('peer_burst', 'f32', False),
                                   ('queue_capacity', 'u64', False),
                                   ('bias_min_scale', 'f32', False),
                                   ('bias_max_handicap_ms', 'u64', False),
                                   ('activity_window_ms', 'u64', False),
                                   ('activity_min_forwards', 'u64', False),
                                   ('activity_idle_windows', 'u32', False)),
             'MessageStats': (('message_id', 'string', False),
                              ('sent_at_ms', 'u64', False),
                              ('delivered_at_ms', 'u64?', False),
                              ('hop_count', 'u8', False),
                              ('status', 'string', False)),
             'MlsAddMemberResult': (('welcome', 'MlsWelcomeMessage', False),
                                    ('commit', 'MlsEncryptedMessage', False)),
             'MlsEncryptedMessage': (('group_id', 'string', False),
                                     ('message_type', 'string', False),
                                     ('epoch', 'u64', False),
                                     ('ciphertext', 'sequence<u8>', False),
                                     ('sender_id', 'string', False),
                                     ('timestamp_ms', 'u64', False)),
             'MlsGroupInfo': (('group_id', 'string', False),
                              ('name', 'string?', False),
                              ('members', 'sequence<string>', False),
                              ('epoch', 'u64', False),
                              ('is_session', 'boolean', False),
                              ('created_at_ms', 'u64', False),
                              ('last_activity_ms', 'u64', False)),
             'MlsKeyPackageBundle': (('package_id', 'string', False),
                                     ('user_id', 'string', False),
                                     ('key_package_data', 'sequence<u8>', False),
                                     ('created_at_ms', 'u64', False),
                                     ('expires_at_ms', 'u64', False),
                                     ('synced', 'boolean', False)),
             'MlsWelcomeMessage': (('group_id', 'string', False),
                                   ('welcome_data', 'sequence<u8>', False),
                                   ('inviter_id', 'string', False),
                                   ('group_name', 'string?', False),
                                   ('timestamp_ms', 'u64', False)),
             'NetworkLink': (('source_id', 'string', False),
                             ('target_id', 'string', False),
                             ('transport', 'string', False),
                             ('quality', 'f32', False)),
             'NetworkNode': (('node_id', 'string', False),
                             ('role', 'string', False),
                             ('rssi', 'i16?', False),
                             ('battery_level', 'u8?', False),
                             ('connection_count', 'u32', False),
                             ('last_seen_ms', 'u64', False)),
             'NetworkTopology': (('nodes', 'sequence<NetworkNode>', False),
                                 ('links', 'sequence<NetworkLink>', False),
                                 ('message_stats', 'sequence<MessageStats>', False)),
             'NostrMessage': (('message_id', 'string', False),
                              ('event_id', 'string', False),
                              ('event_json', 'string', False)),
             'NostrQuery': (('query_id', 'string', False), ('req_json', 'string', False)),
             'PeerDevice': (('peer_id', 'string', False),
                            ('rssi', 'i16', False),
                            ('last_seen_ms', 'u64', False)),
             'PendingQueueConfig': (('max_pending_per_peer', 'u64', False),
                                    ('max_pending_global', 'u64', False),
                                    ('pending_ttl_ms', 'u64', False),
                                    ('overflow_policy', 'OverflowPolicy', False)),
             'ProtocolConfig': (('app_id', 'string', False),
                                ('profile', 'string', False),
                                ('ble_enabled', 'boolean', False),
                                ('wifi_direct_enabled', 'boolean', False),
                                ('internet_enabled', 'boolean', False),
                                ('reticulum_enabled', 'boolean', False),
                                ('nostr_enabled', 'boolean', False),
                                ('prefer_online', 'boolean', False),
                                ('initial_ttl', 'u8', False),
                                ('encryption_enabled', 'boolean', False),
                                ('auto_key_exchange', 'boolean', False),
                                ('store_pending', 'boolean', False),
                                ('require_encryption', 'boolean', True),
                                ('max_pending_per_peer', 'u64', False),
                                ('max_pending_global', 'u64', False),
                                ('pending_ttl_ms', 'u64', False),
                                ('overflow_policy', 'OverflowPolicy', False),
                                ('edge_driven_unreachable_dm', 'boolean', True),
                                ('max_group_members', 'u32', True),
                                ('group_relay_enabled', 'boolean', True),
                                ('group_relay_broadcast_enabled', 'boolean', True),
                                ('group_enforce_admin_commits', 'boolean', True),
                                ('require_transport_identity', 'boolean', True),
                                ('binary_wire_enabled', 'boolean', True),
                                ('nostr_sealing_enabled', 'boolean', True),
                                ('nostr_cold_contact_enabled', 'boolean', True),
                                ('nostr_username_discovery_enabled', 'boolean', True),
                                ('compact_envelope_enabled', 'boolean', True),
                                ('rich_payload_enabled', 'boolean', True),
                                ('crypto_recovery_enabled', 'boolean', True),
                                ('mesh_relay', 'MeshRelayConfig?', True),
                                ('custody', 'CustodyConfig?', True),
                                ('data_enabled', 'boolean', True),
                                ('control_freshness_enforced', 'boolean', True)),
             'ProtocolLockDiagnostics': (('held', 'boolean', False),
                                         ('holder_location', 'string', False),
                                         ('holder_thread', 'string', False),
                                         ('held_for_ms', 'u64', False)),
             'RelayConfig': (('min_battery_for_relay', 'u8', False),
                             ('allow_relay', 'boolean', False),
                             ('relay_priority', 'RelayPriority', False)),
             'ReliabilityConfig': (('ack', 'AckConfig', False),
                                   ('retry', 'RetryConfig', False),
                                   ('dedup', 'DedupConfig', False)),
             'ReplyContext': (('sender', 'string', False),
                              ('text', 'string', False),
                              ('timestamp', 'i64?', True),
                              ('reply_media_label', 'string?', True),
                              ('reply_content_type', 'string?', True)),
             'ReticulumMessage': (('message_id', 'string', False),
                                  ('recipient_id', 'string', False),
                                  ('data', 'sequence<u8>', False),
                                  ('reply_to_msg', 'string?', False)),
             'RetryConfig': (('max_retries', 'u32', False),
                             ('initial_delay_ms', 'u64', False),
                             ('max_delay_ms', 'u64', False),
                             ('backoff_multiplier', 'f32', False),
                             ('outbox_max_lifetime_ms', 'u64', False),
                             ('pending_message_max_lifetime_ms', 'u64', False),
                             ('edge_driven_unreachable_dm', 'boolean', True)),
             'SendMessageOptions': (('priority', 'MessagePriority?', True),
                                    ('reply_to_msg', 'string?', True),
                                    ('content_type', 'ContentType?', True),
                                    ('reply_context', 'ReplyContext?', True),
                                    ('media_metadata', 'MediaMetadata?', True),
                                    ('forward_info', 'ForwardInfo?', True),
                                    ('app_id', 'string?', True)),
             'TelemetryConfig': (('api_key', 'string', False),
                                 ('app_id', 'string', False),
                                 ('os', 'TelemetryOs', False),
                                 ('os_major', 'u16', False),
                                 ('app_version', 'string?', False),
                                 ('debug', 'boolean?', False),
                                 ('flush_interval_ms', 'u64?', False),
                                 ('max_batch_bytes', 'u64?', False),
                                 ('max_buffered_records', 'u32?', False),
                                 ('include_device_id', 'boolean?', False),
                                 ('scrub_ids', 'boolean?', False),
                                 ('mls_verbosity', 'MlsVerbosity?', False),
                                 ('metrics_cadence_ms', 'u64?', False),
                                 ('routing_diagnostic', 'boolean?', False),
                                 ('mls_sampling_bypass', 'boolean?', False)),
             'TelemetryStats': (('buffered', 'u64', False),
                                ('sent_events', 'u64', False),
                                ('accepted_events', 'u64', False),
                                ('dropped', 'u64', False),
                                ('session_id', 'string', False),
                                ('last_error', 'string?', False),
                                ('last_flush_at_ms', 'i64?', False)),
             'TransportConfig': (('ble_enabled', 'boolean', False),
                                 ('wifi_direct_enabled', 'boolean', False),
                                 ('internet_enabled', 'boolean', False),
                                 ('reticulum_enabled', 'boolean', False),
                                 ('nostr_enabled', 'boolean', False),
                                 ('nostr_sealing_enabled', 'boolean', True),
                                 ('nostr_cold_contact_enabled', 'boolean', True),
                                 ('nostr_username_discovery_enabled', 'boolean', True)),
             'TransportMetrics': (('packets_sent', 'u32', False),
                                  ('packets_received', 'u32', False),
                                  ('bytes_sent', 'u32', False),
                                  ('bytes_received', 'u32', False),
                                  ('error_rate', 'f32', False),
                                  ('avg_latency_ms', 'u32', False),
                                  ('rssi', 'i16?', False),
                                  ('bandwidth_bps', 'u64?', False),
                                  ('congestion', 'f32?', False),
                                  ('queue_depth', 'u32?', False),
                                  ('battery_level', 'u8?', False),
                                  ('is_charging', 'boolean?', False),
                                  ('relay_connection_count', 'u8?', False),
                                  ('is_active_relay', 'boolean?', False),
                                  ('delivery_ratio', 'f32?', False),
                                  ('drop_rate', 'f32?', False),
                                  ('average_hop_count', 'f32?', False),
                                  ('energy_cost', 'f32?', False)),
             'WifiDirectMessage': (('recipient_id', 'string', False),
                                   ('data', 'sequence<u8>', False))}}
